name: Basic Checks

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Linting
        run: gradle ktlintCheck
        
      - name: Unit Tests
        run: gradle test
