name: Lint and Test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches-ignore:
      - "main"

jobs:
  caches:
    name: "Initialize Caches"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate Gradle State
        run: ./gradlew compileKotlin

  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    needs: "caches"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Linting
        run: ./gradlew ktlintCheck

  test:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    needs: "caches"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit Tests
        run: ./gradlew test
