name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"

jobs:
  build:
    name: "Lint and Test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Linting
        run: ./gradlew ktlintCheck
        
      - name: Unit Tests
        run: ./gradlew test
