name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  basic-checks:
    name: "Basic Checks"
    uses: ./.github/workflows/basic_checks.yml

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: "basic-checks"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./gradlew build --info --stacktrace
